(in-package :story)

(define-story-module documentation
  :root (namestring (asdf:system-relative-pathname :story-module-documentation ""))
  :imports (("documentation-demo" documentation-demo-template))
  :directories ("docs")
  :depends-on (:polymer :iron-request :files :paper-button :iron-icons :paper-icon-button))

(define-template documentation-demo
  :properties ()
  :style (("#listing" :margin-bottom 20px)
          ("span.doc-entry" :color blue :cursor pointer :display inline-block
                            :padding "6px 10px 6px 10px")
          ("a" :color blue :text-decoration none :cursor pointer))
  :content ((:div :id "top")
            (:div :id "index")
            (:div :id "viewer"
                  (:div :id "controls" (icon-button :icon "arrow-back" :on-tap "viewerBack"))
                  (:div :id "contents"))))

(define-template-method documentation-demo attached ()
  (with-content (top index viewer)
    (hide index)
    (hide viewer)
    (fetch-json "/docs/.file-listing"
                (lambda (val)
                  (loop for el in val
                        do ((@ top append)
                            (dom (:paper-button nil ((style "margin-right:10px;")
                                                     (on-tap "selectDocIndex")
                                                     (value (@ el name))))
                                 (@ el name))))))))

(define-template-method documentation-demo select-doc-index (event)
  (let ((root (+ "/docs/" (@ event target value) "/")))
    (with-content (index viewer)
      (hide viewer)
      (show index)
      (fetch-json (+ root "index.json")
                  (lambda (val)
                    (set-html index "")
                    (loop for el in (@ val entries)
                          do (append-child index (dom (:span "doc-entry" ((entry el)
                                                                          (root root)
                                                                          (on-tap "selectDocEntry")))
                                                      (@ el name)))))))))

(define-template-method documentation-demo select-doc-entry (event)
  (_select-doc-entry (@ event target root) (@ event target entry path)))

(define-template-method documentation-demo _select-doc-entry (root path)
  (console :asd root path)
  (let* ((pos ((@ path index-of) "#"))
         (base (if (plusp pos) ((@ path substr) 0 pos) path))
         (into (when (plusp pos) ((@ path substr) (1+ pos)))))
    (with-content (top index viewer contents)
      (hide index)
      (show viewer)
      (request (+ root base ".html")
               (lambda (val)
                 (set-html contents (@ val response))
                 (loop for link in ((@ contents query-selector-all) "a")
                       when (let ((val (@ link attributes href value)))
                              (not (and val (or ((@ val starts-with) "http")
                                                ((@ val starts-with) "#")))))
                         do (let ((val (@ link attributes href value))
                                  (obj link))
                              (setf (@ link saved-href)
                                    (if ((@ val starts-with) "../")
                                        ((@ val substr) 3)
                                        val))
                              ((@ link remove-attribute) "href")
                              (setf (@ link onclick)
                                    (lambda (event)
                                      ((@ event stop-propagation))
                                      (_select-doc-entry root (@ obj saved-href)))))
                       do (progn
                            (add-class link "documentation-demo")
                            ((@ link set-attribute) "tabindex" 1)))
                 (if into
                     ((@ (id into) scroll-into-view))
                     ((@ top scroll-into-view))))))))

(define-template-method documentation-demo viewer-back (event)
  (with-content (index viewer)
    (hide viewer)
    (show index)))
